# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_max', models.FloatField(default=171.5)),
                ('resign', models.BooleanField(default=False)),
                ('free_agent', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=False)),
                ('final_cuts', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapCasualty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('HB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('ED', 'Edge'), ('LB', 'Inside Linebacker'), ('CB', 'Corner'), ('S', 'Safety')], max_length=2)),
                ('cap_hit', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_round', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('HB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('ED', 'Edge'), ('LB', 'Inside Linebacker'), ('CB', 'Corner'), ('S', 'Safety')], max_length=2)),
                ('cap_hit', models.FloatField()),
                ('draft_round', models.IntegerField()),
                ('college', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('HB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('ED', 'Edge'), ('LB', 'Inside Linebacker'), ('CB', 'Corner'), ('S', 'Safety')], max_length=2)),
                ('cap_hit', models.FloatField()),
                ('on_team', models.BooleanField()),
                ('modified_cost', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('HB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('OL', 'Offensive Line'), ('DL', 'Defensive Line'), ('ED', 'Edge'), ('LB', 'Inside Linebacker'), ('CB', 'Corner'), ('S', 'Safety')], max_length=2)),
                ('cap_hit', models.FloatField()),
                ('dead_money', models.FloatField(blank=True, null=True)),
                ('offer', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
